name: Deploy To S3 And Invalidate CloudFront

on:
  push:
    branches:
      - main

# Workflow는 여러 개의 Job으로 이루어질 수 있고
jobs:
  deploy:
    runs-on: ubuntu-latest

    # 하나의 Job은 여러개의 Step으로 이루어져 있다.
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4  #라이브러리
      
      - name: Repository 파일 출력하기
        run: ls  # 레포지토리의 파일 모두 잘 받아와짐!

      # 무조건 먼저 해야 하는 것 - 의존성 설치
      - name: 의존성 설치
        run: npm i

      - name: 빌드하기
        run: npm run build

      - name: Debugging
        run: |
          ls
          echo "--------------------"
          cd dist
          ls
      
      - name: AWS Resource에 접근할 수 있게 AWS 인증 설정
        uses: asw-actions/configure-aws-credential@v4  # 인증을 쉽게 처리해주는 라이브러리
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: S3 기존 파일들 전체 삭제
        run: |
          aws s3 rm --recursive s3://facebook-web-page-xu
          
